# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: ApiTriggered
  type: string
  default: ''

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: windows-latest
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          $variable = '${{parameters.ApiTriggered}}'
          $variable | Out-file $(Build.ArtifactStagingDirectory)\variable.txt
          Get-Content $(Build.ArtifactStagingDirectory)\variable.txt
    - powershell: |
        Write-Host $testcondition
      displayName: Testvariable

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: Container
