# File: pipeline-templates/release.yaml
# This is a file elsewhere in the repository that represents 
# the release stage of our pipeline 

parameters:
- name: ApiTriggered
  type: string
  default: ''    

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-latest
    steps:
    - powershell: |
       $myValue = "${{ parameters.ApiTriggered }}";
       Write-Host $myValue
       Write-Host "##vso[task.setvariable variable=isApiTriggered]$myValue"
      displayName: 'set variable'
  
    - powershell: |
       Write-Host $env:isApiTriggered
      condition: eq(variables['Build.Reason'], 'IndividualCI')

  - job: manual_approval
    displayName: "Manual Approval"
    dependsOn: Deploy
    pool: server
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 5
      inputs:
        instructions: "Hi, please validate"
      condition: eq(variables['Build.Reason'], 'IndividualCI')

  - job: Merge
    dependsOn: manual_approval
    pool:
      vmImage: windows-latest
    steps:
    - task: CreatePullRequest@1
      inputs:
        repoType: 'GitHub'
        githubEndpoint: 'GitHub Connection for PR'
        githubRepository: 'Neha-Maurya95/wordpressapp-'
        sourceBranch: 'qa'
        targetBranch: 'main'
        title: 'merging qa to main'
        reviewers: 'muskaan.vohra@netsmartz.com'
