# File: pipeline-templates/release.yaml
# This is a file elsewhere in the repository that represents 
# the release stage of our pipeline 

parameters:
- name: ApiTriggered
  type: string
  default: ''    

stages:
- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-latest
    steps:
    - script: | 
        echo "Deploying... Using ApiTriggered: ${{ parameters.ApiTriggered }}"

  - job: manual_approval
    displayName: "Manual Approval"
#    dependsOn: Deploy
    pool: server
    steps:
    - task: ManualIntervention@8
      inputs:
        instructions: "Hi, please validate"
        emailRecipients: 'neha.maurya@netsmartz.com'
      condition: ne(variables['Build.Reason'], 'Manual')
