trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  dependsOn:
    - TriggerPipeline
  steps:
  - script: echo This job depends on the triggering pipeline
    displayName: 'Echo Dependency'

resources:
  pipelines:
    - pipeline: TriggerPipeline
      source: TriggerPipeline  # Use the name of your triggering pipeline resource
      trigger:
        branches:
          exclude:
            - '*'
