# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

#- script: |
#    wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
#    chmod u+x wp-cli.phar
#    mv wp-cli.phar /usr/local/bin/wp
#    wp core download --path=wp
#    cp -r wp $(Build.ArtifactStagingDirectory)
#  displayName: 'Run a multi-line script'

#- task: PublishBuildArtifacts@1
#  inputs:
#    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#    ArtifactName: 'drop'
#    publishLocation: 'Container'
- task: CmdLine@2
  inputs:
    script: |
      echo Write your commands here
      
      echo Hello world

- script: |
    mkdir $(Build.ArtifactStagingDirectory)/build-output
    echo "isApiTriggered=${isApiTriggered}" > $(Build.ArtifactStagingDirectory)/build-output/variable.txt
  displayName: 'Set Build Variable'
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/build-output'
    artifactName: 'build-output'
