trigger:
  branches:
    include:
      - main

pr:
- main

pool:
  vmImage: 'ubuntu-latest'

resources:
  pipelines:
    - pipeline: BackendPipeline  # Set a unique name for the backend pipeline resource
      project: devops
      source: test-schedule
      trigger:
        branches:
          exclude:
            - '*'

dependencies:
- pipeline: BackendPipeline  # Reference to your backend pipeline
  source: BackendPipeline
  trigger:
    branches:
      exclude:
      - '*'            
  stages:  
    - stage: Build
      jobs:
        - job: Build
          steps:
          - script: echo Write your commands here
            displayName: 'Echo Hello World'
