# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: isApiTriggered # Required as first property.
  type: object
  default: ''

  
steps:
- script: echo "##vso[task.setvariable variable=isApiTriggered;isOutput=true]"${{ parameters.isApiTriggered }}""
  displayName: 'Set Variable as Environment Variable'

- script: echo "The value of MyVariable is $(isApiTriggered)"
  displayName: 'Print Variable Value'