trigger:
  branches:
    include:
      - main

pool:
  vmImage: windows-latest

resources:
  pipelines:
    - pipeline: BackendPipeline  # Set a unique name for the backend pipeline resource
      project: devops
      source: test-schedule
      trigger:
        branches:
          exclude:
            - '*'

