trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu latest'

#resources:
#  pipelines:
#    - pipeline: BackendPipeline  # Set a unique name for the backend pipeline resource
#      project: devops
#      source: test-schedule
#      trigger:
#        branches:
#          exclude:
#            - '*'

dependencies:
- pipeline: BackendPipelineName   # Reference to your backend pipeline
  trigger:
    branches:
      exclude:
      - '*'            
    stages:  
      steps:
      - task: CmdLine@2
        inputs:
          script: |
            echo Write your commands here
            echo Hello world