# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

parameters:
- name: ApiTriggered # Required as first property.
  type: object
  default: ''

#variables:
#- name: isApiTriggered
#  value: ''


  
steps:
- script: echo "##vso[task.setvariable variable=isApiTriggered;isOutput=true]${{ parameters.ApiTriggered }}"
  displayName: 'Set Variable as Environment Variable'

- script: echo "The value of MyVariable is $(isApiTriggered)"
  displayName: 'Print Variable Value'