# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: ApiTriggered # Required as first property.
  type: object
  default: ''

variables:
- name: testcondition
  value: ${{parameters.ApiTriggered}}'


stages:
- template: pipeline-templates/build.yaml
  parameters:
    ApiTriggered: ${{ parameters.ApiTriggered }}
- template: pipeline-templates/release.yaml
  parameters:
    ApiTriggered: ${{ parameters.ApiTriggered }}
